// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Referral struct {
	ReferralCodeID uuid.UUID `json:"referral_code_id"`
	UserID         uuid.UUID `json:"user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type ReferralCode struct {
	ID           uuid.UUID      `json:"id"`
	Title        sql.NullString `json:"title"`
	Code         string         `json:"code"`
	ReferralLink sql.NullString `json:"referral_link"`
	IsPersonal   sql.NullBool   `json:"is_personal"`
	UserID       uuid.NullUUID  `json:"user_id"`
	CreatedAt    time.Time      `json:"created_at"`
}
