// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Referral struct {
	ReferralCodeID uuid.UUID `json:"referral_code_id"`
	UserID         uuid.UUID `json:"user_id"`
	CreatedAt      time.Time `json:"created_at"`
}
