// Code generated by sqlc. DO NOT EDIT.
// source: referrals.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getReferralCodeByID = `-- name: GetReferralCodeByID :one
SELECT referral_code_id
FROM referrals
WHERE user_id = $1
`

func (q *Queries) GetReferralCodeByID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.getReferralCodeByIDStmt, getReferralCodeByID, userID)
	var referral_code_id uuid.UUID
	err := row.Scan(&referral_code_id)
	return referral_code_id, err
}
