// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Episode struct {
	ID            uuid.UUID      `json:"id"`
	ShowID        uuid.UUID      `json:"show_id"`
	EpisodeNumber int32          `json:"episode_number"`
	Cover         sql.NullString `json:"cover"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ReleaseDate   sql.NullTime   `json:"release_date"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Show struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Cover         string         `json:"cover"`
	HasNewEpisode bool           `json:"has_new_episode"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	CreatedAt     time.Time      `json:"created_at"`
	Description   sql.NullString `json:"description"`
}

type ShowsCategory struct {
	ID           uuid.UUID    `json:"id"`
	CategoryName string       `json:"category_name"`
	Title        string       `json:"title"`
	Disabled     sql.NullBool `json:"disabled"`
}

type ShowsToCategory struct {
	CategoryID uuid.UUID `json:"category_id"`
	ShowID     uuid.UUID `json:"show_id"`
}
