// Code generated by sqlc. DO NOT EDIT.
// source: shows_categories.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addShowCategory = `-- name: AddShowCategory :one
INSERT INTO shows_categories (
    sort,
    title,
    disabled
)
VALUES (
           $1,
           $2,
           $3
       ) RETURNING id, title, disabled, sort
`

type AddShowCategoryParams struct {
	Sort     int32        `json:"sort"`
	Title    string       `json:"title"`
	Disabled sql.NullBool `json:"disabled"`
}

func (q *Queries) AddShowCategory(ctx context.Context, arg AddShowCategoryParams) (ShowsCategory, error) {
	row := q.queryRow(ctx, q.addShowCategoryStmt, addShowCategory, arg.Sort, arg.Title, arg.Disabled)
	var i ShowsCategory
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Disabled,
		&i.Sort,
	)
	return i, err
}

const deleteShowCategoryByID = `-- name: DeleteShowCategoryByID :exec
DELETE FROM shows_categories
WHERE id = $1
`

func (q *Queries) DeleteShowCategoryByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteShowCategoryByIDStmt, deleteShowCategoryByID, id)
	return err
}

const getShowCategories = `-- name: GetShowCategories :many
SELECT id, title, disabled, sort
FROM shows_categories
WHERE disabled = FALSE
ORDER BY sort DESC
    LIMIT $1 OFFSET $2
`

type GetShowCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetShowCategories(ctx context.Context, arg GetShowCategoriesParams) ([]ShowsCategory, error) {
	rows, err := q.query(ctx, q.getShowCategoriesStmt, getShowCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowsCategory
	for rows.Next() {
		var i ShowsCategory
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Disabled,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowCategoryByID = `-- name: GetShowCategoryByID :one
SELECT id, title, disabled, sort
FROM shows_categories
WHERE id = $1
`

func (q *Queries) GetShowCategoryByID(ctx context.Context, id uuid.UUID) (ShowsCategory, error) {
	row := q.queryRow(ctx, q.getShowCategoryByIDStmt, getShowCategoryByID, id)
	var i ShowsCategory
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Disabled,
		&i.Sort,
	)
	return i, err
}

const updateShowCategory = `-- name: UpdateShowCategory :exec
UPDATE shows_categories
SET sort = $1,
    title = $2,
    disabled = $3
WHERE id = $4
`

type UpdateShowCategoryParams struct {
	Sort     int32        `json:"sort"`
	Title    string       `json:"title"`
	Disabled sql.NullBool `json:"disabled"`
	ID       uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateShowCategory(ctx context.Context, arg UpdateShowCategoryParams) error {
	_, err := q.exec(ctx, q.updateShowCategoryStmt, updateShowCategory,
		arg.Sort,
		arg.Title,
		arg.Disabled,
		arg.ID,
	)
	return err
}
