// Code generated by sqlc. DO NOT EDIT.
// source: shows.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addShow = `-- name: AddShow :one
WITH inserted_shows AS(

INSERT INTO shows (
    title,
    cover,
    has_new_episode,
    description
  )
VALUES (
           $1,
           $2,
           $3,
           $4
       ) RETURNING id, title, cover, has_new_episode, updated_at, created_at, description )
SELECT id, title, cover, has_new_episode, updated_at, created_at, description, category_id, show_id FROM inserted_shows
LEFT JOIN shows_to_category
ON shows_to_category.id = shows_to_category.show_id
`

type AddShowParams struct {
	Title         string         `json:"title"`
	Cover         string         `json:"cover"`
	HasNewEpisode bool           `json:"has_new_episode"`
	Description   sql.NullString `json:"description"`
}

type AddShowRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Cover         string         `json:"cover"`
	HasNewEpisode bool           `json:"has_new_episode"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	CreatedAt     time.Time      `json:"created_at"`
	Description   sql.NullString `json:"description"`
	CategoryID    uuid.UUID      `json:"category_id"`
	ShowID        uuid.UUID      `json:"show_id"`
}

func (q *Queries) AddShow(ctx context.Context, arg AddShowParams) (AddShowRow, error) {
	row := q.queryRow(ctx, q.addShowStmt, addShow,
		arg.Title,
		arg.Cover,
		arg.HasNewEpisode,
		arg.Description,
	)
	var i AddShowRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.HasNewEpisode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Description,
		&i.CategoryID,
		&i.ShowID,
	)
	return i, err
}

const deleteShowByID = `-- name: DeleteShowByID :exec
DELETE FROM shows
WHERE id = $1
`

func (q *Queries) DeleteShowByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteShowByIDStmt, deleteShowByID, id)
	return err
}

const getShowByID = `-- name: GetShowByID :one
SELECT id, title, cover, has_new_episode, updated_at, created_at, description, category_id, show_id
FROM shows
LEFT JOIN shows_to_category
ON id = show_id
WHERE id = $1
`

type GetShowByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Cover         string         `json:"cover"`
	HasNewEpisode bool           `json:"has_new_episode"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	CreatedAt     time.Time      `json:"created_at"`
	Description   sql.NullString `json:"description"`
	CategoryID    uuid.UUID      `json:"category_id"`
	ShowID        uuid.UUID      `json:"show_id"`
}

func (q *Queries) GetShowByID(ctx context.Context, id uuid.UUID) (GetShowByIDRow, error) {
	row := q.queryRow(ctx, q.getShowByIDStmt, getShowByID, id)
	var i GetShowByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.HasNewEpisode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Description,
		&i.CategoryID,
		&i.ShowID,
	)
	return i, err
}

const getShows = `-- name: GetShows :many
SELECT id, title, cover, has_new_episode, updated_at, created_at, description, category_id, show_id
FROM shows
LEFT JOIN shows_to_category
ON id = show_id
ORDER BY has_new_episode DESC,
    updated_at DESC,
    created_at DESC
LIMIT $1 OFFSET $2
`

type GetShowsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetShowsRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Cover         string         `json:"cover"`
	HasNewEpisode bool           `json:"has_new_episode"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	CreatedAt     time.Time      `json:"created_at"`
	Description   sql.NullString `json:"description"`
	CategoryID    uuid.UUID      `json:"category_id"`
	ShowID        uuid.UUID      `json:"show_id"`
}

func (q *Queries) GetShows(ctx context.Context, arg GetShowsParams) ([]GetShowsRow, error) {
	rows, err := q.query(ctx, q.getShowsStmt, getShows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsRow
	for rows.Next() {
		var i GetShowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Cover,
			&i.HasNewEpisode,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Description,
			&i.CategoryID,
			&i.ShowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShow = `-- name: UpdateShow :exec
UPDATE shows
SET title = $1,
    cover = $2,
    has_new_episode = $3,
    description = $4
WHERE id = $5
`

type UpdateShowParams struct {
	Title         string         `json:"title"`
	Cover         string         `json:"cover"`
	HasNewEpisode bool           `json:"has_new_episode"`
	Description   sql.NullString `json:"description"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateShow(ctx context.Context, arg UpdateShowParams) error {
	_, err := q.exec(ctx, q.updateShowStmt, updateShow,
		arg.Title,
		arg.Cover,
		arg.HasNewEpisode,
		arg.Description,
		arg.ID,
	)
	return err
}
