// Code generated by sqlc. DO NOT EDIT.
// source: shows.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addShow = `-- name: AddShow :one
INSERT INTO shows (
    title,
    cover,
    has_new_episode,
    category,
    description,
    realms_title,
    realms_subtitle,
    watch
  )
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8
) RETURNING id, title, cover, has_new_episode, updated_at, created_at, category, description, realms_title, realms_subtitle, watch, archived
`

type AddShowParams struct {
	Title          string         `json:"title"`
	Cover          string         `json:"cover"`
	HasNewEpisode  bool           `json:"has_new_episode"`
	Category       sql.NullString `json:"category"`
	Description    sql.NullString `json:"description"`
	RealmsTitle    sql.NullString `json:"realms_title"`
	RealmsSubtitle sql.NullString `json:"realms_subtitle"`
	Watch          sql.NullString `json:"watch"`
}

func (q *Queries) AddShow(ctx context.Context, arg AddShowParams) (Show, error) {
	row := q.queryRow(ctx, q.addShowStmt, addShow,
		arg.Title,
		arg.Cover,
		arg.HasNewEpisode,
		arg.Category,
		arg.Description,
		arg.RealmsTitle,
		arg.RealmsSubtitle,
		arg.Watch,
	)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.HasNewEpisode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Category,
		&i.Description,
		&i.RealmsTitle,
		&i.RealmsSubtitle,
		&i.Watch,
		&i.Archived,
	)
	return i, err
}

const deleteShowByID = `-- name: DeleteShowByID :exec
DELETE FROM shows
WHERE id = $1
`

func (q *Queries) DeleteShowByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteShowByIDStmt, deleteShowByID, id)
	return err
}

const getShowByID = `-- name: GetShowByID :one
WITH show_claps_sum AS (
    SELECT 
        COUNT(*) AS claps,
        show_id
    FROM show_claps
    WHERE show_id = $1
    GROUP BY show_id  
)
SELECT 
    shows.id, shows.title, shows.cover, shows.has_new_episode, shows.updated_at, shows.created_at, shows.category, shows.description, shows.realms_title, shows.realms_subtitle, shows.watch, shows.archived,
    COALESCE(show_claps_sum.claps, 0) as claps
FROM shows
LEFT JOIN show_claps_sum ON show_claps_sum.show_id = shows.id
WHERE shows.id = $1 AND shows.archived = FALSE
`

type GetShowByIDRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Cover          string         `json:"cover"`
	HasNewEpisode  bool           `json:"has_new_episode"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	CreatedAt      time.Time      `json:"created_at"`
	Category       sql.NullString `json:"category"`
	Description    sql.NullString `json:"description"`
	RealmsTitle    sql.NullString `json:"realms_title"`
	RealmsSubtitle sql.NullString `json:"realms_subtitle"`
	Watch          sql.NullString `json:"watch"`
	Archived       bool           `json:"archived"`
	Claps          int64          `json:"claps"`
}

func (q *Queries) GetShowByID(ctx context.Context, id uuid.UUID) (GetShowByIDRow, error) {
	row := q.queryRow(ctx, q.getShowByIDStmt, getShowByID, id)
	var i GetShowByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.HasNewEpisode,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Category,
		&i.Description,
		&i.RealmsTitle,
		&i.RealmsSubtitle,
		&i.Watch,
		&i.Archived,
		&i.Claps,
	)
	return i, err
}

const getShows = `-- name: GetShows :many
SELECT id, title, cover, has_new_episode, updated_at, created_at, category, description, realms_title, realms_subtitle, watch, archived
FROM shows
WHERE archived = FALSE
ORDER BY has_new_episode DESC,
    updated_at DESC,
    created_at DESC
LIMIT $1 OFFSET $2
`

type GetShowsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetShows(ctx context.Context, arg GetShowsParams) ([]Show, error) {
	rows, err := q.query(ctx, q.getShowsStmt, getShows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Cover,
			&i.HasNewEpisode,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Category,
			&i.Description,
			&i.RealmsTitle,
			&i.RealmsSubtitle,
			&i.Watch,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowsByCategory = `-- name: GetShowsByCategory :many
SELECT id, title, cover, has_new_episode, updated_at, created_at, category, description, realms_title, realms_subtitle, watch, archived FROM shows
WHERE id IN(
        SELECT DISTINCT show_id FROM shows_to_categories
              JOIN show_categories ON show_categories.id = shows_to_categories.category_id
        WHERE show_categories.disabled = FALSE
          AND show_categories.id = $1)
ORDER BY has_new_episode DESC,
         updated_at DESC,
         created_at DESC
    LIMIT $3 OFFSET $2
`

type GetShowsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Offset     int32     `json:"offset_val"`
	Limit      int32     `json:"limit_val"`
}

func (q *Queries) GetShowsByCategory(ctx context.Context, arg GetShowsByCategoryParams) ([]Show, error) {
	rows, err := q.query(ctx, q.getShowsByCategoryStmt, getShowsByCategory, arg.CategoryID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Cover,
			&i.HasNewEpisode,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Category,
			&i.Description,
			&i.RealmsTitle,
			&i.RealmsSubtitle,
			&i.Watch,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShow = `-- name: UpdateShow :exec
UPDATE shows
SET title = $1,
    cover = $2,
    has_new_episode = $3,
    category = $4,
    description = $5,
    realms_title = $6,
    realms_subtitle = $7,
    watch = $8
WHERE id = $9
`

type UpdateShowParams struct {
	Title          string         `json:"title"`
	Cover          string         `json:"cover"`
	HasNewEpisode  bool           `json:"has_new_episode"`
	Category       sql.NullString `json:"category"`
	Description    sql.NullString `json:"description"`
	RealmsTitle    sql.NullString `json:"realms_title"`
	RealmsSubtitle sql.NullString `json:"realms_subtitle"`
	Watch          sql.NullString `json:"watch"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateShow(ctx context.Context, arg UpdateShowParams) error {
	_, err := q.exec(ctx, q.updateShowStmt, updateShow,
		arg.Title,
		arg.Cover,
		arg.HasNewEpisode,
		arg.Category,
		arg.Description,
		arg.RealmsTitle,
		arg.RealmsSubtitle,
		arg.Watch,
		arg.ID,
	)
	return err
}
