// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"
)

type ExchangeRate struct {
	AssetType string       `json:"asset_type"`
	UsdPrice  float64      `json:"usd_price"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedAt time.Time    `json:"created_at"`
}
