// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Wallet struct {
	ID            uuid.UUID     `json:"id"`
	UserID        uuid.UUID     `json:"user_id"`
	AssetName     string        `json:"asset_name"`
	WalletAddress string        `json:"wallet_address"`
	PublicKey     string        `json:"public_key"`
	PrivateKey    string        `json:"private_key"`
	Status        sql.NullInt32 `json:"status"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	CreatedAt     time.Time     `json:"created_at"`
}
