// Code generated by sqlc. DO NOT EDIT.
// source: stake_level.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addStakeLevel = `-- name: AddStakeLevel :one
INSERT INTO stake_levels (
        min_stake_amount,
        title,
        subtitle,
        multiplier
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    ) ON CONFLICT (title) DO NOTHING RETURNING id, min_stake_amount, title, subtitle, multiplier
`

type AddStakeLevelParams struct {
	MinStakeAmount sql.NullFloat64 `json:"min_stake_amount"`
	Title          string          `json:"title"`
	Subtitle       string          `json:"subtitle"`
	Multiplier     sql.NullInt32   `json:"multiplier"`
}

func (q *Queries) AddStakeLevel(ctx context.Context, arg AddStakeLevelParams) (StakeLevel, error) {
	row := q.queryRow(ctx, q.addStakeLevelStmt, addStakeLevel,
		arg.MinStakeAmount,
		arg.Title,
		arg.Subtitle,
		arg.Multiplier,
	)
	var i StakeLevel
	err := row.Scan(
		&i.ID,
		&i.MinStakeAmount,
		&i.Title,
		&i.Subtitle,
		&i.Multiplier,
	)
	return i, err
}

const getAllStakeLevels = `-- name: GetAllStakeLevels :many
SELECT id, min_stake_amount, title, subtitle, multiplier
FROM stake_levels
ORDER BY min_stake_amount ASC
`

func (q *Queries) GetAllStakeLevels(ctx context.Context) ([]StakeLevel, error) {
	rows, err := q.query(ctx, q.getAllStakeLevelsStmt, getAllStakeLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StakeLevel
	for rows.Next() {
		var i StakeLevel
		if err := rows.Scan(
			&i.ID,
			&i.MinStakeAmount,
			&i.Title,
			&i.Subtitle,
			&i.Multiplier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStakeLevelByID = `-- name: GetStakeLevelByID :one
SELECT id, min_stake_amount, title, subtitle, multiplier
FROM stake_levels
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStakeLevelByID(ctx context.Context, id uuid.UUID) (StakeLevel, error) {
	row := q.queryRow(ctx, q.getStakeLevelByIDStmt, getStakeLevelByID, id)
	var i StakeLevel
	err := row.Scan(
		&i.ID,
		&i.MinStakeAmount,
		&i.Title,
		&i.Subtitle,
		&i.Multiplier,
	)
	return i, err
}

const updateStakeLevel = `-- name: UpdateStakeLevel :exec
UPDATE stake_levels
SET min_stake_amount = $2, title = $3, subtitle = $4, multiplier = $5
WHERE id = $1
`

type UpdateStakeLevelParams struct {
	ID             uuid.UUID       `json:"id"`
	MinStakeAmount sql.NullFloat64 `json:"min_stake_amount"`
	Title          string          `json:"title"`
	Subtitle       string          `json:"subtitle"`
	Multiplier     sql.NullInt32   `json:"multiplier"`
}

func (q *Queries) UpdateStakeLevel(ctx context.Context, arg UpdateStakeLevelParams) error {
	_, err := q.exec(ctx, q.updateStakeLevelStmt, updateStakeLevel,
		arg.ID,
		arg.MinStakeAmount,
		arg.Title,
		arg.Subtitle,
		arg.Multiplier,
	)
	return err
}
