// Code generated by sqlc. DO NOT EDIT.
// source: token_transfers.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTokenTransfer = `-- name: AddTokenTransfer :one
INSERT INTO token_transfers (user_id, sender_address, recipient_address, amount, tx_hash, status)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) RETURNING id, user_id, sender_address, recipient_address, tx_hash, amount, status, updated_at, created_at
`

type AddTokenTransferParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	SenderAddress    string         `json:"sender_address"`
	RecipientAddress string         `json:"recipient_address"`
	Amount           float64        `json:"amount"`
	TxHash           sql.NullString `json:"tx_hash"`
	Status           int32          `json:"status"`
}

func (q *Queries) AddTokenTransfer(ctx context.Context, arg AddTokenTransferParams) (TokenTransfer, error) {
	row := q.queryRow(ctx, q.addTokenTransferStmt, addTokenTransfer,
		arg.UserID,
		arg.SenderAddress,
		arg.RecipientAddress,
		arg.Amount,
		arg.TxHash,
		arg.Status,
	)
	var i TokenTransfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SenderAddress,
		&i.RecipientAddress,
		&i.TxHash,
		&i.Amount,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTokenTransfer = `-- name: UpdateTokenTransfer :exec
UPDATE token_transfers
SET status = $1,
    tx_hash = $2
WHERE id = $3
`

type UpdateTokenTransferParams struct {
	Status int32          `json:"status"`
	TxHash sql.NullString `json:"tx_hash"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTokenTransfer(ctx context.Context, arg UpdateTokenTransferParams) error {
	_, err := q.exec(ctx, q.updateTokenTransferStmt, updateTokenTransfer, arg.Status, arg.TxHash, arg.ID)
	return err
}
