// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Qrcode struct {
	ID           uuid.UUID       `json:"id"`
	ShowID       uuid.UUID       `json:"show_id"`
	EpisodeID    uuid.UUID       `json:"episode_id"`
	StartsAt     time.Time       `json:"starts_at"`
	ExpiresAt    time.Time       `json:"expires_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	CreatedAt    time.Time       `json:"created_at"`
	RewardAmount sql.NullFloat64 `json:"reward_amount"`
}

type ScannedQrcode struct {
	UserID    uuid.UUID    `json:"user_id"`
	QrcodeID  uuid.UUID    `json:"qrcode_id"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedAt time.Time    `json:"created_at"`
}
