// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SatorNetwork/sator-api/lib/mail (interfaces: Interface)

// Package mail is a generated GoMock package.
package mail

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// SendDestroyAccountCode mocks base method.
func (m *MockInterface) SendDestroyAccountCode(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDestroyAccountCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDestroyAccountCode indicates an expected call of SendDestroyAccountCode.
func (mr *MockInterfaceMockRecorder) SendDestroyAccountCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDestroyAccountCode", reflect.TypeOf((*MockInterface)(nil).SendDestroyAccountCode), arg0, arg1, arg2)
}

// SendInvitation mocks base method.
func (m *MockInterface) SendInvitation(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvitation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvitation indicates an expected call of SendInvitation.
func (mr *MockInterfaceMockRecorder) SendInvitation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvitation", reflect.TypeOf((*MockInterface)(nil).SendInvitation), arg0, arg1, arg2)
}

// SendResetPasswordCode mocks base method.
func (m *MockInterface) SendResetPasswordCode(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResetPasswordCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResetPasswordCode indicates an expected call of SendResetPasswordCode.
func (mr *MockInterfaceMockRecorder) SendResetPasswordCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResetPasswordCode", reflect.TypeOf((*MockInterface)(nil).SendResetPasswordCode), arg0, arg1, arg2)
}

// SendVerificationCode mocks base method.
func (m *MockInterface) SendVerificationCode(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationCode indicates an expected call of SendVerificationCode.
func (mr *MockInterfaceMockRecorder) SendVerificationCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationCode", reflect.TypeOf((*MockInterface)(nil).SendVerificationCode), arg0, arg1, arg2)
}
