// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Challenge struct {
	ID              uuid.UUID      `json:"id"`
	ShowID          uuid.UUID      `json:"show_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	PrizePool       float64        `json:"prize_pool"`
	PlayersToStart  int32          `json:"players_to_start"`
	TimePerQuestion sql.NullInt32  `json:"time_per_question"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
}
