// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID      `json:"id"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Password   []byte         `json:"password"`
	Disabled   bool           `json:"disabled"`
	VerifiedAt sql.NullTime   `json:"verified_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	CreatedAt  time.Time      `json:"created_at"`
	Role       sql.NullString `json:"role"`
}

type UserVerification struct {
	RequestType      int32     `json:"request_type"`
	UserID           uuid.UUID `json:"user_id"`
	Email            string    `json:"email"`
	VerificationCode []byte    `json:"verification_code"`
	CreatedAt        time.Time `json:"created_at"`
}
