// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: flags.sql

package repository

import (
	"context"
)

const createFlag = `-- name: CreateFlag :exec
INSERT INTO flags (
    key,
    value
) VALUES (
    $1,
    $2
) ON CONFLICT DO NOTHING
`

type CreateFlagParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) error {
	_, err := q.exec(ctx, q.createFlagStmt, createFlag, arg.Key, arg.Value)
	return err
}

const getFlagByKey = `-- name: GetFlagByKey :one
SELECT key, value
FROM flags
WHERE key = $1
`

func (q *Queries) GetFlagByKey(ctx context.Context, key string) (Flag, error) {
	row := q.queryRow(ctx, q.getFlagByKeyStmt, getFlagByKey, key)
	var i Flag
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}
