// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createPuzzleGameStmt, err = db.PrepareContext(ctx, createPuzzleGame); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePuzzleGame: %w", err)
	}
	if q.getPuzzleGameByEpisodeIDStmt, err = db.PrepareContext(ctx, getPuzzleGameByEpisodeID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPuzzleGameByEpisodeID: %w", err)
	}
	if q.getPuzzleGameByIDStmt, err = db.PrepareContext(ctx, getPuzzleGameByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPuzzleGameByID: %w", err)
	}
	if q.linkImageToPuzzleGameStmt, err = db.PrepareContext(ctx, linkImageToPuzzleGame); err != nil {
		return nil, fmt.Errorf("error preparing query LinkImageToPuzzleGame: %w", err)
	}
	if q.unlinkImageFromPuzzleGameStmt, err = db.PrepareContext(ctx, unlinkImageFromPuzzleGame); err != nil {
		return nil, fmt.Errorf("error preparing query UnlinkImageFromPuzzleGame: %w", err)
	}
	if q.updatePuzzleGameStmt, err = db.PrepareContext(ctx, updatePuzzleGame); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePuzzleGame: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createPuzzleGameStmt != nil {
		if cerr := q.createPuzzleGameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPuzzleGameStmt: %w", cerr)
		}
	}
	if q.getPuzzleGameByEpisodeIDStmt != nil {
		if cerr := q.getPuzzleGameByEpisodeIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPuzzleGameByEpisodeIDStmt: %w", cerr)
		}
	}
	if q.getPuzzleGameByIDStmt != nil {
		if cerr := q.getPuzzleGameByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPuzzleGameByIDStmt: %w", cerr)
		}
	}
	if q.linkImageToPuzzleGameStmt != nil {
		if cerr := q.linkImageToPuzzleGameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing linkImageToPuzzleGameStmt: %w", cerr)
		}
	}
	if q.unlinkImageFromPuzzleGameStmt != nil {
		if cerr := q.unlinkImageFromPuzzleGameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unlinkImageFromPuzzleGameStmt: %w", cerr)
		}
	}
	if q.updatePuzzleGameStmt != nil {
		if cerr := q.updatePuzzleGameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePuzzleGameStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	createPuzzleGameStmt          *sql.Stmt
	getPuzzleGameByEpisodeIDStmt  *sql.Stmt
	getPuzzleGameByIDStmt         *sql.Stmt
	linkImageToPuzzleGameStmt     *sql.Stmt
	unlinkImageFromPuzzleGameStmt *sql.Stmt
	updatePuzzleGameStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		createPuzzleGameStmt:          q.createPuzzleGameStmt,
		getPuzzleGameByEpisodeIDStmt:  q.getPuzzleGameByEpisodeIDStmt,
		getPuzzleGameByIDStmt:         q.getPuzzleGameByIDStmt,
		linkImageToPuzzleGameStmt:     q.linkImageToPuzzleGameStmt,
		unlinkImageFromPuzzleGameStmt: q.unlinkImageFromPuzzleGameStmt,
		updatePuzzleGameStmt:          q.updatePuzzleGameStmt,
	}
}
