// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addNewChallegeRoomStmt, err = db.PrepareContext(ctx, addNewChallegeRoom); err != nil {
		return nil, fmt.Errorf("error preparing query AddNewChallegeRoom: %w", err)
	}
	if q.getChallengeRoomByChallengeIDStmt, err = db.PrepareContext(ctx, getChallengeRoomByChallengeID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChallengeRoomByChallengeID: %w", err)
	}
	if q.getChallengeRoomByIDStmt, err = db.PrepareContext(ctx, getChallengeRoomByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChallengeRoomByID: %w", err)
	}
	if q.updateChallengeRoomStatusStmt, err = db.PrepareContext(ctx, updateChallengeRoomStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChallengeRoomStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addNewChallegeRoomStmt != nil {
		if cerr := q.addNewChallegeRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addNewChallegeRoomStmt: %w", cerr)
		}
	}
	if q.getChallengeRoomByChallengeIDStmt != nil {
		if cerr := q.getChallengeRoomByChallengeIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChallengeRoomByChallengeIDStmt: %w", cerr)
		}
	}
	if q.getChallengeRoomByIDStmt != nil {
		if cerr := q.getChallengeRoomByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChallengeRoomByIDStmt: %w", cerr)
		}
	}
	if q.updateChallengeRoomStatusStmt != nil {
		if cerr := q.updateChallengeRoomStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChallengeRoomStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	addNewChallegeRoomStmt            *sql.Stmt
	getChallengeRoomByChallengeIDStmt *sql.Stmt
	getChallengeRoomByIDStmt          *sql.Stmt
	updateChallengeRoomStatusStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		addNewChallegeRoomStmt:            q.addNewChallegeRoomStmt,
		getChallengeRoomByChallengeIDStmt: q.getChallengeRoomByChallengeIDStmt,
		getChallengeRoomByIDStmt:          q.getChallengeRoomByIDStmt,
		updateChallengeRoomStatusStmt:     q.updateChallengeRoomStatusStmt,
	}
}
