// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type TradingPlatformLink struct {
	ID        uuid.UUID    `json:"id"`
	Title     string       `json:"title"`
	Link      string       `json:"link"`
	Logo      string       `json:"logo"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedAt time.Time    `json:"created_at"`
}
