// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SatorNetwork/sator-api/lib/nft_marketplace (interfaces: Interface)

// Package nft_marketplace is a generated GoMock package.
package nft_marketplace

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// PrepareBuyTx mocks base method.
func (m *MockInterface) PrepareBuyTx(arg0 *PrepareBuyTxRequest) (*PrepareBuyTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareBuyTx", arg0)
	ret0, _ := ret[0].(*PrepareBuyTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareBuyTx indicates an expected call of PrepareBuyTx.
func (mr *MockInterfaceMockRecorder) PrepareBuyTx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareBuyTx", reflect.TypeOf((*MockInterface)(nil).PrepareBuyTx), arg0)
}

// SendPreparedBuyTx mocks base method.
func (m *MockInterface) SendPreparedBuyTx(arg0 *SendPreparedBuyTxRequest) (*SendPreparedBuyTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPreparedBuyTx", arg0)
	ret0, _ := ret[0].(*SendPreparedBuyTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPreparedBuyTx indicates an expected call of SendPreparedBuyTx.
func (mr *MockInterfaceMockRecorder) SendPreparedBuyTx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPreparedBuyTx", reflect.TypeOf((*MockInterface)(nil).SendPreparedBuyTx), arg0)
}
