// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addRewardStmt, err = db.PrepareContext(ctx, addReward); err != nil {
		return nil, fmt.Errorf("error preparing query AddReward: %w", err)
	}
	if q.getTotalAmountStmt, err = db.PrepareContext(ctx, getTotalAmount); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalAmount: %w", err)
	}
	if q.getUserRewardsByStatusStmt, err = db.PrepareContext(ctx, getUserRewardsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRewardsByStatus: %w", err)
	}
	if q.withdrawStmt, err = db.PrepareContext(ctx, withdraw); err != nil {
		return nil, fmt.Errorf("error preparing query Withdraw: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addRewardStmt != nil {
		if cerr := q.addRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addRewardStmt: %w", cerr)
		}
	}
	if q.getTotalAmountStmt != nil {
		if cerr := q.getTotalAmountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalAmountStmt: %w", cerr)
		}
	}
	if q.getUserRewardsByStatusStmt != nil {
		if cerr := q.getUserRewardsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRewardsByStatusStmt: %w", cerr)
		}
	}
	if q.withdrawStmt != nil {
		if cerr := q.withdrawStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing withdrawStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	addRewardStmt              *sql.Stmt
	getTotalAmountStmt         *sql.Stmt
	getUserRewardsByStatusStmt *sql.Stmt
	withdrawStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		addRewardStmt:              q.addRewardStmt,
		getTotalAmountStmt:         q.getTotalAmountStmt,
		getUserRewardsByStatusStmt: q.getUserRewardsByStatusStmt,
		withdrawStmt:               q.withdrawStmt,
	}
}
