// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createIAPReceiptStmt, err = db.PrepareContext(ctx, createIAPReceipt); err != nil {
		return nil, fmt.Errorf("error preparing query CreateIAPReceipt: %w", err)
	}
	if q.createIapProductStmt, err = db.PrepareContext(ctx, createIapProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateIapProduct: %w", err)
	}
	if q.getIAPReceiptByTxIDStmt, err = db.PrepareContext(ctx, getIAPReceiptByTxID); err != nil {
		return nil, fmt.Errorf("error preparing query GetIAPReceiptByTxID: %w", err)
	}
	if q.getIapProductByIDStmt, err = db.PrepareContext(ctx, getIapProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetIapProductByID: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createIAPReceiptStmt != nil {
		if cerr := q.createIAPReceiptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createIAPReceiptStmt: %w", cerr)
		}
	}
	if q.createIapProductStmt != nil {
		if cerr := q.createIapProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createIapProductStmt: %w", cerr)
		}
	}
	if q.getIAPReceiptByTxIDStmt != nil {
		if cerr := q.getIAPReceiptByTxIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIAPReceiptByTxIDStmt: %w", cerr)
		}
	}
	if q.getIapProductByIDStmt != nil {
		if cerr := q.getIapProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIapProductByIDStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	createIAPReceiptStmt    *sql.Stmt
	createIapProductStmt    *sql.Stmt
	getIAPReceiptByTxIDStmt *sql.Stmt
	getIapProductByIDStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		createIAPReceiptStmt:    q.createIAPReceiptStmt,
		createIapProductStmt:    q.createIapProductStmt,
		getIAPReceiptByTxIDStmt: q.getIAPReceiptByTxIDStmt,
		getIapProductByIDStmt:   q.getIapProductByIDStmt,
	}
}
