// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IapProduct struct {
	ID         string       `json:"id"`
	PriceInSao float64      `json:"price_in_sao"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type IapReceipt struct {
	ID            uuid.UUID    `json:"id"`
	TransactionID string       `json:"transaction_id"`
	ReceiptData   string       `json:"receipt_data"`
	ReceiptInJson string       `json:"receipt_in_json"`
	UserID        uuid.UUID    `json:"user_id"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	CreatedAt     time.Time    `json:"created_at"`
}
