name: Go

on:
  push:
    branches: [main, develop, SAT-719-cannot-unlock-tokens]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, develop, SAT-719-cannot-unlock-tokens]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up application
        run: make -f Makefile.ci up && sleep 10 && make -f Makefile.ci migrate-local

      - name: Run e2e tests
        run: sleep 10 && make -f Makefile.ci e2e-tests

      - name: Run integration tests
        run: sleep 10 && make -f Makefile.ci integration-tests

      - name: Archive sator-api log file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: sator-api.log
          path: sator-api.log
