name: Go

on:
  push:
    branches: [quiz-v2, refactor-quiz-engine-v2]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up application
        run: make -f Makefile.ci up && sleep 10 && make -f Makefile.ci migrate-local run-local

      - name: Run e2e tests
        run: make -f Makefile.ci test
