// Code generated by sqlc. DO NOT EDIT.
// source: relations.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addNFTRelation = `-- name: AddNFTRelation :exec
INSERT INTO nft_relations (nft_item_id, relation_id)
VALUES ($1, $2)
`

type AddNFTRelationParams struct {
	NFTItemID  uuid.UUID `json:"nft_item_id"`
	RelationID uuid.UUID `json:"relation_id"`
}

func (q *Queries) AddNFTRelation(ctx context.Context, arg AddNFTRelationParams) error {
	_, err := q.exec(ctx, q.addNFTRelationStmt, addNFTRelation, arg.NFTItemID, arg.RelationID)
	return err
}

const deleteNFTRelation = `-- name: DeleteNFTRelation :exec
DELETE FROM nft_relations
WHERE nft_item_id = $1
AND relation_id = $2
`

type DeleteNFTRelationParams struct {
	NFTItemID  uuid.UUID `json:"nft_item_id"`
	RelationID uuid.UUID `json:"relation_id"`
}

func (q *Queries) DeleteNFTRelation(ctx context.Context, arg DeleteNFTRelationParams) error {
	_, err := q.exec(ctx, q.deleteNFTRelationStmt, deleteNFTRelation, arg.NFTItemID, arg.RelationID)
	return err
}

const doesRelationIDHasRelationNFT = `-- name: DoesRelationIDHasRelationNFT :one
SELECT EXISTS(
    SELECT nft_item_id FROM nft_relations
    WHERE relation_id = $1
)
`

func (q *Queries) DoesRelationIDHasRelationNFT(ctx context.Context, relationID uuid.UUID) (bool, error) {
	row := q.queryRow(ctx, q.doesRelationIDHasRelationNFTStmt, doesRelationIDHasRelationNFT, relationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
